# Generated by Django 4.2.5 on 2023-09-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=31)),
                ('sharif', models.CharField(max_length=31)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('telefon_raqam', models.CharField(max_length=17)),
                ('tugilgan_sana', models.DateTimeField()),
                ('malumot', models.TextField()),
                ('toifa', models.IntegerField(choices=[(1, 'Birinchi toifa'), (2, 'Ikkinchi toifa')])),
                ('jins', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=31)),
                ('sharif', models.CharField(max_length=31)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('telefon_raqam', models.CharField(max_length=17)),
                ('tugilgan_sana', models.DateTimeField()),
                ('xizmat', models.IntegerField(default=0)),
                ('ustoz', models.ManyToManyField(related_name='mijozlar', to='mentors.ustoz')),
            ],
        ),
    ]
