# Generated by Django 4.2.5 on 2023-09-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
        ('products', '0003_product_created_time_product_updated_time'),
    ]

    operations = [
    ]
